name = "ITensorModels"
uuid = "ef2189cb-6e0f-43f0-8f34-d6f851ec88d5"
version = "0.1.0"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
