name = "ITensorModels"
uuid = "ef2189cb-6e0f-43f0-8f34-d6f851ec88d5"
version = "0.5.1"
authors = ["sota shimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensorSiteKit = "ffe6b83a-dc94-4fa6-83e9-b4b377faf66b"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[weakdeps]
LatticeCore = "84b1cbd8-bc58-4618-bc4f-b46a399f49f1"
QAtlas = "2bd488d2-d3e6-46ee-afb3-5515643db0c7"

[sources.ITensorSiteKit]
rev = "v0.1.0"
url = "https://github.com/sotashimozono/ITensorSiteKit.jl"

[extensions]
LatticeCoreExt = "LatticeCore"
QAtlasExt = "QAtlas"

[compat]
ITensorMPS = "0.3"
ITensorSiteKit = "0.1"
ITensors = "0.9"
LatticeCore = "0.8"
QAtlas = "0.13, 0.14, 0.15"
julia = "1.10"

[extras]
Lattice2D = "e8031020-b7ff-4f1d-bee4-f79aea4cf140"
LatticeCore = "84b1cbd8-bc58-4618-bc4f-b46a399f49f1"
QAtlas = "2bd488d2-d3e6-46ee-afb3-5515643db0c7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Lattice2D", "LatticeCore", "QAtlas", "Random", "Test"]
